import streamlit as st
import pandas as pd
import os

# --- PAGE CONFIG ---
st.set_page_config(page_title="Quotation Generator", layout="wide")

# --- 1. DATA LOADER ---
@st.cache_data(show_spinner=True)
def load_data():
    """
    Reads the 'FIXED_MASTER_LIST.xlsx' generated by the converter script.
    """
    # Check possible locations for the file
    file_path = "data/FIXED_MASTER_LIST.xlsx"
    if not os.path.exists(file_path):
        if os.path.exists("FIXED_MASTER_LIST.xlsx"):
            file_path = "FIXED_MASTER_LIST.xlsx"
        else:
            return pd.DataFrame(), False

    try:
        xls = pd.ExcelFile(file_path)
        all_data = []
        
        for sheet in xls.sheet_names:
            df = pd.read_excel(xls, sheet)
            df['Category'] = sheet # Use Sheet Name as Category
            all_data.append(df)
            
        final_df = pd.concat(all_data, ignore_index=True)
        return final_df, True
    except Exception as e:
        st.error(f"Error reading clean file: {e}")
        return pd.DataFrame(), False

# --- 2. LOAD DATA ---
catalog, file_found = load_data()

# --- 3. SESSION STATE ---
if 'cart' not in st.session_state: st.session_state['cart'] = []

# --- 4. SIDEBAR (ADD ITEMS) ---
with st.sidebar:
    st.title("🔧 Config")
    
    if st.button("🔄 Refresh Data"):
        st.cache_data.clear()
        st.rerun()

    if not file_found:
        st.error("❌ 'data/FIXED_MASTER_LIST.xlsx' not found!")
        st.warning("Please run the 'convert_data.py' script first to generate the data.")
    
    else:
        st.header("1. Add Item")
        
        # A. FILTERING
        cats = sorted(catalog['Category'].unique())
        sel_cat = st.selectbox("Category", cats)
        
        subset = catalog[catalog['Category'] == sel_cat]
        prods = sorted(subset['Item Description'].unique())
        sel_prod = st.selectbox("Product", prods)
        
        # B. GET DETAILS
        row = subset[subset['Item Description'] == sel_prod].iloc[0]
        
        std_price = float(row['List Price'])
        std_disc = float(row.get('Standard Discount', 0))
        uom = row.get('UOM', 'Unit')
        coil_len = float(row.get('Coil Length (Mtr)', 0))
        
        # C. DISPLAY INFO
        st.info(f"**Rate:** ₹{std_price:,.2f} / {uom}\n\nStd Disc: {std_disc}%")
        
        # D. QUANTITY INPUT LOGIC (COIL VS METER)
        calc_qty = 0
        display_unit = uom
        
        st.markdown("---")
        
        # Logic: If it has a Coil Length defined AND it is sold per Meter
        if coil_len > 0 and uom == "Mtr":
            st.write(f"ℹ️ **Standard Coil:** {int(coil_len)} Meters")
            
            mode = st.radio("Input Mode:", ["Coils", "Meters"], horizontal=True)
            
            if mode == "Coils":
                qty_input = st.number_input(f"Number of Coils", 1, 1000, 1)
                calc_qty = qty_input * coil_len
                st.write(f"➝ Total: **{calc_qty:,.0f} Meters**")
                display_unit = f"Mtr ({qty_input} Coils)"
            else:
                qty_input = st.number_input(f"Total Meters", 1, 100000, 100)
                calc_qty = qty_input
                approx_coils = qty_input / coil_len
                st.caption(f"(Approx {approx_coils:.1f} Coils)")
                display_unit = "Mtr"
        else:
            # Standard input for Glands, Armored Cables (Cut lengths)
            qty_input = st.number_input(f"Quantity ({uom})", 1, 100000, 1)
            calc_qty = qty_input
            display_unit = uom

        # E. MAKE & DISCOUNT
        c1, c2 = st.columns(2)
        disc = c1.number_input("Discount %", 0.0, 100.0, std_disc)
        make_val = c2.text_input("Make", placeholder="e.g. Polycab")
        
        # F. ADD BUTTON
        if st.button("Add to Quote", type="primary"):
            st.session_state['cart'].append({
                'Category': sel_cat,
                'Description': sel_prod,
                'Make': make_val,
                'Qty': calc_qty,         # The raw number for math
                'Display Unit': display_unit, # The text for the table
                'List Price': std_price,
                'Discount': disc,
                'GST Rate': 18.0
            })
            st.success("Added!")

    st.markdown("---")
    st.header("2. Table Columns")
    
    # Options for columns (Ensure 'Make' is available)
    available_cols = ["Make", "Category", "List Price", "Discount %", "Net Rate", "GST %", "GST Amount"]
    default_cols = ["Make", "List Price", "Discount %", "Net Rate", "GST Amount"]
    
    selected_cols = st.multiselect("Select Extra Columns:", available_cols, default=default_cols)
    
    if st.button("🗑️ Clear Entire Cart"):
        st.session_state['cart'] = []
        st.rerun()

# --- 5. MAIN PAGE ---
st.title("📄 Quotation System")

if not st.session_state['cart']:
    st.info("👈 Add items from the sidebar to start.")
else:
    # --- A. REVIEW SECTION (DELETE ITEMS) ---
    st.subheader("1. Review Items")
    
    # Custom Header for Review
    cols = st.columns([0.5, 4, 1.5, 1.5, 2, 0.5])
    headers = ["#", "Description", "Make", "Qty", "Total", ""]
    for c, h in zip(cols, headers): c.markdown(f"**{h}**")
    st.markdown("---")

    # List Items
    for i, item in enumerate(st.session_state['cart']):
        lp = item['List Price']
        disc_val = item['Discount']
        q = item['Qty']
        g_rate = item.get('GST Rate', 18.0)
        
        net = lp * (1 - disc_val/100)
        gst = net * (g_rate/100)
        tot = (net + gst) * q
        
        c1, c2, c3, c4, c5, c6 = st.columns([0.5, 4, 1.5, 1.5, 2, 0.5])
        
        c1.write(f"{i+1}")
        c2.write(item['Description'])
        c3.write(item.get('Make', '-'))
        c4.write(f"{item.get('Display Unit', q)}") 
        c5.write(f"₹ {tot:,.0f}")
        
        # DELETE BUTTON
        if c6.button("🗑️", key=f"del_{i}"):
            st.session_state['cart'].pop(i)
            st.rerun()

    st.divider()
    
    # --- B. FINAL TABLE SECTION ---
    st.subheader("2. Final Draft")
    
    data = []
    grand_total = 0
    
    for i, item in enumerate(st.session_state['cart']):
        lp = item['List Price']
        disc_val = item['Discount']
        qty = item['Qty']
        gst_rate = item.get('GST Rate', 18.0)
        
        net_rate = lp * (1 - disc_val/100)
        gst_amt = net_rate * (gst_rate/100)
        unit_total = net_rate + gst_amt
        line_total = unit_total * qty
        grand_total += line_total
        
        row = {
            "No": i+1,
            "Description": item['Description'],
            "Make": item.get('Make', ''),
            "Qty": f"{qty:,.2f}", 
            "Unit": item.get('Display Unit', '-'), 
            "Category": item['Category'],
            "List Price": f"{lp:,.2f}",
            "Discount %": f"{disc_val}%",
            "Net Rate": f"{net_rate:,.2f}",
            "GST %": f"{gst_rate}%",
            "GST Amount": f"{gst_amt:,.2f}",
            "Total": f"{line_total:,.2f}"
        }
        data.append(row)
    
    # Dynamic Column Selection
    final_cols = ["No", "Description"] 
    if "Make" in selected_cols: final_cols.append("Make")
    
    final_cols += ["Qty", "Unit"]
    
    for c in selected_cols:
        if c not in final_cols: final_cols.append(c)
        
    final_cols.append("Total")
    
    df_disp = pd.DataFrame(data)
    
    # Ensure all cols exist
    for c in final_cols:
        if c not in df_disp.columns: df_disp[c] = ""
        
    st.table(df_disp[final_cols].set_index("No"))
    
    st.markdown(f"### Grand Total: ₹ {grand_total:,.2f}")
    
    st.markdown("""
    <button onclick="window.print()" style="
        background-color: #4CAF50; color: white; 
        padding: 12px 28px; border: none; border-radius: 5px; 
        font-size: 16px; cursor: pointer;">
        🖨️ Print / Save PDF
    </button>
    """, unsafe_allow_html=True)